development:
  adapter: postgresql
  database: myapp_database_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: myapp_database_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: myapp_database
  pool: 5
  timeout: 5000
